### ISSUE TITLE
Cannot install package using `bash setup.sh install`

### ISSUE THREAD

**Issue by h4k1m0u** [hollstein/S2MSI#1]
Hi,

I tried to install this package using the command: `bash setup.sh install` as you mentioned in the README file but I'm getting the following error:

```
Best match: scikit-image 0.13.0
Processing scikit-image-0.13.0.tar.gz
Writing /tmp/easy_install-0k9wj0ca/scikit-image-0.13.0/setup.cfg
Running scikit-image-0.13.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0k9wj0ca/scikit-image-0.13.0/egg-dist-tmp-t1yq5jbf
error: SandboxViolation: mkdir('/root/.config/matplotlib', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
-> bad exit status -> exit here
```

I'm using Archlinux where both `python3.6` and `python2.7` are installed. I've also changed this line `py27env=python2` in the `setup.sh` file but I can't understand the error thrown!

**Comment by hollstein** [comment]
Hi, thanks for reporting. I haven't seen this error. However, development of this package (which is still beta, but working for me and a couple of users) moved to a different repository: 

https://gitext.gfz-potsdam.de/hollstei/sicor

It is used for processing Sentinel-2 data but currently lacks some documentation.

Hope this helps.

Best, André
